const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const React = require('react');
const {renderToStaticMarkup} = require('react-dom/server');
const Module = require('module');
const source = fs.readFileSync('app/dashboard-client.tsx', 'utf8');
const component = source.slice(source.indexOf('function ManagerPanel('), source.indexOf('function AgentPanel('));
const compiled = ts.transpileModule(`const fa=n=>new Intl.NumberFormat('fa-IR').format(n); const fullToman=r=>new Intl.NumberFormat('fa-IR',{maximumFractionDigits:1}).format(r/10); const textOf=x=>x||''; const Status=()=>null; ${component}; exports.ManagerPanel=ManagerPanel;`, {compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS}}).outputText;
const mod = new Module(process.cwd()+'/manager-test.cjs', module);
mod.paths = Module._nodeModulePaths(process.cwd()); mod._compile(compiled, mod.filename || 'manager-test.cjs');
const a = {headline:'گزارش مدیریتی نقدینگی و تعهدات',summary:'ارزیابی',report_context:{version:'v112',actual_from:'2026-09-08',actual_to:'2026-09-08',opening_available:false},executive_kpis:[{group:'actual',label:'حواله پرداختی',value_rial:123456789123,format:'money',available:true},{group:'forecast',label:'مانده پایان بازه',value_rial:null,format:'money',available:false}],recommended_actions:[{action:'تطبیق',owner:'خزانه',deadline:'امروز'}]};
const html=renderToStaticMarkup(React.createElement(mod.exports.ManagerPanel,{a}));
assert(html.includes('۱۲٬۳۴۵٬۶۷۸٬۹۱۲٫۳'));
assert(html.includes('در انتظار داده معتبر'));
assert(html.includes('نیازمند موجودی شروع معتبر'));
assert(html.includes('سه اقدام اولویت‌دار'));
assert(!html.includes('پیش‌بینی پایان ماه'));
assert(!html.includes('تراز تصمیم'));
const old=renderToStaticMarkup(React.createElement(mod.exports.ManagerPanel,{a:{headline:'stale',executive_kpis:a.executive_kpis}}));
assert(old.includes('اجرای همه Agentها')); assert(!old.includes('stale'));
const cash=source.slice(source.indexOf('<section className="fd-kpis cash-bank-kpis">'),source.indexOf('<article className="fd-panel commitment-summary">'));
assert(cash.includes('summary.bank_payment_total_rial'));
assert(cash.includes('summary.bank_payment_excluding_transfer_rial'));
console.log('PASS: exact Toman, missing data, Persian sections, stale report gate, two payment totals');
