const fs = require('fs');
const assert = require('assert');
const source = fs.readFileSync(require('path').join(__dirname, '..', 'app', 'dashboard-client.tsx'), 'utf8');
assert(source.includes('فیلتر محل / وضعیت چک دریافتی'));
assert(source.includes('نزد مأمور وصول'));
assert(source.includes('نزد بانک'));
assert(source.includes('نزد صندوق'));
assert(source.includes('receivedChequeHoldingBucket'));
assert(source.includes('c.state_code === 2'));
assert(source.includes('c.state_code === 1'));
assert(source.includes('واگذار\\s*شده'));
console.log('received cheque holding filter source checks OK');
